"use client";
import { useEffect, useState } from "react";

export default function Privacy() {
  const [email, setEmail] = useState("");

  useEffect(() => {
    const user = "k";
    const domain = "abs.gd";
    setEmail(`${user}@${domain}`);
  }, []);

  return (
    <main className="max-w-6xl mx-auto mt-25 px-4">
      <h1 className="text-5xl">Privacy Policy for kayleigh.page</h1>
      <p className="italic mt-2">Effective Date: April 10, 2025</p>
      <h2 className="text-3xl mt-8">1. Introduction</h2>
      <p className="mt-2">
        Welcome to{" "}
        <a
          href="https://kayleigh.page"
          className="text-blue-600 underline cursor-pointer hover:text-blue-800 hover:no-underline"
        >
          kayleigh.page
        </a>{" "}
        (&quot;we,&quot; &quot;our,&quot; &quot;us&quot;). We are committed
        to protecting your privacy and ensuring that your personal
        information is handled in a safe and responsible manner. This
        Privacy Policy outlines how we collect, use, and protect your
        information when you visit our website.
      </p>
      <h2 className="text-3xl mt-8">2. Information We Collect</h2>
      <p className="mt-2">
        <strong>Personal Data:</strong> When you contact us directly via
        email at{" "}
        <a
          href={`mailto:${email}`}
          className="text-blue-600 underline cursor-pointer hover:text-blue-800 hover:no-underline"
        >
          {email}
        </a>
        , we may collect your name, email address, and any other information
        you provide.
      </p>
      <p className="mt-2">
        <strong>Usage Data:</strong> We collect information about your
        interactions with our website, such as IP addresses, browser types,
        pages visited, and the time and date of your visit. This data helps
        us understand how our website is used and improve our services.
      </p>
      <p className="mt-2">
        <strong>Newsletter Subscription Data:</strong> When you subscribe to
        our newsletter, we collect your email address to send you updates
        and promotional content.
      </p>
      <p className="mt-2">
        <strong>Service Inquiries:</strong> When you contact us via email to
        inquire about our services, we collect your name, email address, and
        any additional information you provide related to your project
        needs.
      </p>
      <h2 className="text-3xl mt-8">3. Useage of Collected Data</h2>
      <h3 className="text-xl mt-4">
        Google Analytics and Google Tag Manager
      </h3>
      <p className="mt-2">
        We use Google Analytics and Google Tag Manager to analyze the use of
        our website. These services collect data through cookies and similar
        technologies to track and report website traffic. The information
        generated by these cookies about your use of our website is
        transmitted to and stored by Google on servers that may be located
        outside the European Economic Area (EEA).
      </p>
      <p className="mt-2">
        Google uses this information to evaluate your use of our website,
        compile reports on website activity, and provide other services
        related to website activity and internet usage. For more information
        on how Google collects and processes data, please visit
        Google&apos;s Privacy Policy:{" "}
        <a
          href="https://policies.google.com/privacy"
          className="text-blue-600 underline cursor-pointer hover:text-blue-800 hover:no-underline"
        >
          https://policies.google.com/privacy
        </a>
        .
      </p>
      <h3 className="text-xl mt-4">Newsletter Subscription</h3>
      <p className="mt-2">
        Your email address is used exclusively to send you our newsletter
        and related promotional materials.​
      </p>
      <h3 className="text-xl mt-4">Service Communications</h3>
      <p className="mt-2">
        We use the information collected from service inquiries to respond
        to your requests, discuss project details, provide quotations, and
        establish potential contractual agreements.​
      </p>

      <h2 className="text-3xl mt-8">4. Legal Basis for Processing</h2>
      <p className="mt-2">
        We process your personal data based on the following legal grounds:
      </p>
      <p className="mt-2">
        <strong>Consent:</strong> By using our website, you consent to the
        collection and use of your information as described in this Privacy
        Policy. By subscribing to our newsletter, you provide explicit
        consent for us to use your email address for this purpose.
      </p>
      <p className="mt-2">
        <strong>Legitimate Interests:</strong> We process usage data to
        improve our website&apos;s functionality and user experience.
      </p>

      <h2 className="text-3xl mt-8">5. Data Sharing and Disclosure</h2>
      <p className="mt-2">
        We do not sell, trade, or otherwise transfer your personal data to
        outside parties, except as described below:
      </p>
      <p className="mt-2">
        <strong>Service Providers:</strong> We may share your information
        with third-party service providers who assist us in operating our
        website and conducting our business, subject to confidentiality
        agreements.
      </p>
      <p className="mt-2">
        <strong>Legal Requirements:</strong> We may disclose your
        information if required to do so by law or in response to valid
        requests by public authorities.
      </p>
      <p className="mt-2">
        <strong>Third-Party Collaboration:</strong> In certain cases, we may
        share your information with trusted partners or subcontractors to
        fulfill specific aspects of your project. Such sharing will occur
        only with your explicit consent, and all parties involved are
        obligated to maintain the confidentiality and security of your
        information.
      </p>

      <h2 className="text-3xl mt-8">6. Data Retention</h2>
      <p className="mt-2">
        We retain your personal data only for as long as is necessary for
        the purposes set out in this Privacy Policy. Usage data collected
        via Google Analytics is retained for 26 months.
      </p>
      <p className="mt-2">
        We retain your email address as long as you remain subscribed to our
        newsletter. If you unsubscribe, your email will be removed from our
        mailing list promptly. Every email contains a clear unsubscribe
        link. You can also email us to unsubscribe at any moment.
      </p>
      <p className="mt-2">
        We retain information from service inquiries for a period of 12
        months from the date of the last communication. This allows us to
        refer back to previous discussions if you decide to proceed with our
        services at a later date. If a formal contract is established, the
        information will be retained in accordance with our contractual data
        retention policies.
      </p>

      <h2 className="text-3xl mt-8">7. Your Rights Under GDPR</h2>
      <p className="mt-2">
        As a resident of Europe, you have the following rights under the
        GDPR:
      </p>
      <p className="mt-2">
        <strong>Access:</strong> You have the right to request copies of
        your personal data.
      </p>
      <p className="mt-2">
        <strong>Rectification:</strong> You have the right to request that
        we correct any information you believe is inaccurate or complete
        information you believe is incomplete.
      </p>
      <p className="mt-2">
        <strong>Erasure:</strong> You have the right to request that we
        erase your personal data, under certain conditions.
      </p>
      <p className="mt-2">
        <strong>Restriction of Processing:</strong> You have the right to
        request that we restrict the processing of your personal data, under
        certain conditions.
      </p>
      <p className="mt-2">
        <strong>Objection to Processing:</strong> You have the right to
        object to our processing of your personal data, under certain
        conditions.
      </p>
      <p className="mt-2">
        <strong>Data Portability:</strong> You have the right to request
        that we transfer the data that we have collected to another
        organization, or directly to you, under certain conditions.
      </p>
      <p className="mt-2">
        To exercise any of these rights, please contact us at{" "}
        <a
          href={`mailto:${email}`}
          className="text-blue-600 underline cursor-pointer hover:text-blue-800 hover:no-underline"
        >
          {email}
        </a>
        .
      </p>
      <h2 className="text-3xl mt-8">
        8. Cookies and Tracking Technologies
      </h2>
      <p className="mt-2">
        We use cookies to enhance your experience on our website. You can
        set your browser to refuse all or some browser cookies or to alert
        you when cookies are being sent. Please note that disabling cookies
        may affect the functionality of our website.
      </p>
      <h2 className="text-3xl mt-8">9. International Data Transfers</h2>
      <p className="mt-2">
        Given that our website is hosted in the Netherlands and we are based
        in Belgium, your information may be transferred to, and maintained
        on, computers located outside of your country or other governmental
        jurisdiction where the data protection laws may differ.
      </p>
      <h2 className="text-3xl mt-8">10. Changes to This Privacy Policy</h2>
      <p className="mt-2">
        We may update our Privacy Policy from time to time. We will notify
        you of any changes by posting the new Privacy Policy on this page
        with an updated effective date.
      </p>
      <h2 className="text-3xl mt-8">11. Contact Us</h2>
      <p className="mt-2">
        If you have any questions about this Privacy Policy, please contact
        us at:
      </p>
      <p className="mt-2">
        <strong>Email:</strong>
        <a
          href={`mailto:${email}`}
          className="text-blue-600 underline cursor-pointer hover:text-blue-800 hover:no-underline"
        >
          {email}
        </a>
      </p>
    </main>
  );
}
